/*
		This file has been auto-generated by WebbotLib tools V1.1
				** DO NOT MODIFY BY HAND **
*/
#ifndef _LIB_HARDWARE_C_
#define _LIB_HARDWARE_C_
#include "../hardware.h"
#  define USART0_TX_vect USART_TX_vect
#  define USART0_RX_vect USART_RX_vect

// ------------------- myUart -------------------

// Create a routine to write bytes to myUart
// You can set rprintf to use it by calling rprintfInit(&myUartSendByte)
MAKE_WRITER(myUartSendByte){
	return uartSendByte(myUart,byte);
}

// Create a routine to read a byte from myUart
// Returns -1 if there was no data
MAKE_READER( myUartGetByte){
	return uartGetByte(myUart);
}

// Create hardware UART myUart
HW_UART _myUart = MAKE_HW_UART(UCSR0A,UCSR0B,UBRR0L,UBRR0H,UDR0,null,BV(U2X0),D0,D1,&myUartGetByte,&myUartSendByte);

#ifndef USART0_TX_vect
# error Uart0 Tx complete vector undefined
#else
ISR(USART0_TX_vect){
	uartTransmitService(myUart);
}
#endif

#ifndef USART0_RX_vect
# error Uart0 Rx complete vector undefined
#else
ISR(USART0_RX_vect){
	uartReceiveService(myUart);
}
#endif

// ----------- Define the ADC channels ----------
const uint8_t NUM_ADC_CHANNELS = 6;

// ----------- My devices -----------------------
LED led = MAKE_LED(B5,false);
// Create I2C receive byte array and wrap it in a buffer
static uint8_t i2cSlaveRx[128];
static cBuffer i2cSlaveRxBuffer = MAKE_BUFFER(i2cSlaveRx);
	
// Create I2C transmit byte array and wrap it in a buffer
static uint8_t i2cSlaveTx[32];
static cBuffer i2cSlaveTxBuffer = MAKE_BUFFER(i2cSlaveTx);
static int	stream_put(char c, FILE* f){
	Writer w = (Writer)fdev_get_udata(f);
	return (w) ? w(c) : EOF;
}
static FILE _stdout_= FDEV_SETUP_STREAM(&stream_put,null,_FDEV_SETUP_WRITE);
static FILE _stderr_= FDEV_SETUP_STREAM(&stream_put,null,_FDEV_SETUP_WRITE);

// ----------- Initialise built in devices ------
void sysInitHardware(void){
}

// ----------- Initialise my added devices ------
void initHardware(void){
	i2cSlaveInit(0x9E, true, &i2cSlaveRxBuffer, &i2cSlaveTxBuffer);
	setErrorLog(&myUartSendByte);
	stderr = &_stderr_;
	fdev_set_udata(stderr, &myUartSendByte);
	uartInit(myUart,19200);
	speechInit(B2);
	rprintfInit(getSpeechWriter());
	stdout = &_stdout_;
	fdev_set_udata(stdout, getSpeechWriter());
}
// ----------- Register the statusLED -----------
void registerLED(void){
}

#endif
