/*
		This file has been auto-generated by WebbotLib tools V1.1
				** DO NOT MODIFY BY HAND **
*/
#ifndef LIB_IOPINS_H
#define LIB_IOPINS_H
#include <libdefs.h>
#ifdef __cplusplus
extern "C" {
#endif

// ----------- Define the used pins ------------
extern const IOPin PROGMEM _B0;
extern const IOPin PROGMEM _B1;
extern const IOPin PROGMEM _B2;
extern const IOPin PROGMEM _B3;
extern const IOPin PROGMEM _B5;
extern const IOPin PROGMEM _D0;
extern const IOPin PROGMEM _D1;
extern const IOPin PROGMEM _D3;
extern const IOPin PROGMEM _D5;
extern const IOPin PROGMEM _D6;
#define B0 &_B0
#define B1 &_B1
#define B2 &_B2
#define B3 &_B3
#define B5 &_B5
#define D0 &_D0
#define D1 &_D1
#define D3 &_D3
#define D5 &_D5
#define D6 &_D6
#ifdef __cplusplus
}
#endif
#endif
